disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Stormvault"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "stormvault_logo_transparent-512x512.png"
secondaryLogo = "false"
description = "What if the problem is not that you're not finding enough new clients, but that you're not reaching the right people, in the right way?"

  [params.author]
  image = "stormvault_logo.png"
  name = "Stormvault Networks"
  email = "nicolas@stormvault.net"
  imageQuality = 96
  headline = "Sheltering Brick & Mortar SMBs from Technical Storms."
  links = [ ]

["params.author"]
image = "stormvault_logo_transparent-512x512.png"
name = "Stormvault Networks"
headline = "Reach the right people, the right way, at the perfect time―every time."
bio = ""
