# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "Blog"
 pageRef = "posts"
 weight = 10

# [[main]]
#   name = "Docs"
#   pageRef = "docs"
#   weight = 15

# [[main]]
#   name = "Shortcodes"
#   pageRef = "docs/shortcodes"
#   weight = 20

# [[main]]
#   name = "Examples"
#   weight = 25

# [[main]]
#   name = "Samples"
#   parent = "Examples"
#   pageRef = "samples"
#   weight = 26


[[main]]
 name = "Services"
 weight = 20

  [[main]]
   name = "Enterprise Calls"   # Enterprise Calls: Track. Route. Never Miss.
   parent = "Services"
   pageRef = "/services/enterprise-calls"
   URL = "/services/enterprise-calls"
   weight = 21
 
  # [[main]]
  #  name = "Instant Forms"
  #  parent = "Services"
  #  pageRef = "services/instant-forms"
  #  URL = "/services/instant-forms"
  #  weight = 22


# [[main]]
#  name = "Sales"
#  parent = "Support"
#  pageRef = "/support/sales"
#  weight = 23

# [[main]]
#   name = "Showcase"
#   parent = "Examples"
#   pageRef = "examples"
#   weight = 30

# [[main]]
#   name = "Recipes"
#   parent = "Examples"
#   pageRef = "guides"
#   weight = 40

# [[main]]
#   name = "Users"
#   pageRef = "users"
#   weight = 60

# [[main]]
#   name = "Merch"
#   url = "https://www.teepublic.com/user/blowfish-store/t-shirts"
#   weight = 70


# [[main]]
#  name = "Support"
#  weight = 80

#      [[main]]
#       name = "Help Center"
#       parent = "Support"
#       pageRef = "support/help"
#       URL = "/support/contact"
#       weight = 81

#      [[main]]
#       name = "Contact Us"
#       parent = "Support"
#       pageRef = "support/contact"
#       URL = "/support/contact"
#       weight = 82

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

# [[main]]
#   identifier = "twitter"
#   pre = "x-twitter"
#   url = "https://twitter.com/burufugu"
#   weight = 200

#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"

# [[main]]
#   identifier = "github"
#   pre = "github"
#   url = "https://github.com/nunocoracao/blowfish"
#   weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "Tags"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "Authors"
   pageRef = "authors"
   weight = 20


