# Blowfish theme for Hugo

name = "Stormvault"
license = "MIT"
licenselink = "https://github.com/stormvault/stormvault.net/"
escription = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

homepage = "https://github.com/stormvault/stormvault.net/"

tags = ["blog", "minimal", "responsive", "dark mode", "dark", "light", "tailwind", "personal"]
features = ["syntax highlighting", "dark mode", "emoji", "firebase", "views"]

[author]
  name = "Stormvault Networks"
  homepage = "https://www.stormvault.net/"

[original]
  name = "Stormvault Networks"
  homepage = "https://www.stormvault.net/"
  repo = "https://github.com/stormvault"
